create table revoked_token
(
    id               serial
        primary key,
    expiration_date  timestamp(6),
    jwt_token_digest varchar(255),
    revocation_date  timestamp(6)
);

create table person
(
    id              integer generated by default as identity
        primary key,
    username        varchar(100) not null
        unique,
    password        varchar(100) not null,
    year_of_birth   integer
        constraint person_year_of_birth_check
            check (year_of_birth >= 1900),
    email           varchar(100) not null,
    activation_code varchar(255),
    is_enabled      boolean      not null,
    role            varchar(100) not null
);